/*
 * Auto-generated by Frida. Please modify to match the signature of SecItemAdd.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: http://www.frida.re/docs/javascript-api/
 */

{
    /**
     * Called synchronously when about to call SecItemAdd.
     *
     * @this {object} - Object allowing you to store state for use in onLeave.
     * @param {function} log - Call this function with a string to be presented to the user.
     * @param {array} args - Function arguments represented as an array of NativePointer objects.
     * For example use Memory.readUtf8String(args[0]) if the first argument is a pointer to a C string encoded as UTF-8.
     * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
     * @param {object} state - Object allowing you to keep state across function calls.
     * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
     * However, do not use this to store function arguments across onEnter/onLeave, but instead
     * use "this" which is an object for keeping state local to an invocation.
     */
    onEnter: function (log, args, state) {
				log("[+] Keychain operation: SecItemAdd");
				var params = ObjC.Object(args[0]); // CFDictionaryRef => NSDictionary
				var keys = params.allKeys();
				for (index = 0; index < keys.count(); index++) {
					var k = keys.objectAtIndex_(index);
					var v = params.objectForKey_(k);
					if (k == "v_Data") {
						var string = ObjC.classes.NSString.alloc();
						v = string.initWithData_encoding_(v,4).toString();
					}
					if (k == "pdmn") {
              if (v == "ak") {
                v = "kSecAttrAccessibleWhenUnlocked";
              } else if (v == "ck") {
                v = "kSecAttrAccessibleAfterFirstUnlock";
              } else if (v == "dk") {
                v = "kSecAttrAccessibleAlways";
              } else if (v == "aku") {
                v = "kSecAttrAccessibleWhenUnlockedThisDeviceOnly"
              } else if (v == "cku") {
                v = "kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly";
              } else {
                // v == dku
                v = "kSecAttrAccessibleAlwaysThisDeviceOnly";
              } 
          } 
					log("\t-   " + k + "=" + v);
				}
    },

    /**
     * Called synchronously when about to return from SecItemAdd.
     *
     * See onEnter for details.
     *
     * @this {object} - Object allowing you to access state stored in onEnter.
     * @param {function} log - Call this function with a string to be presented to the user.
     * @param {NativePointer} retval - Return value represented as a NativePointer object.
     * @param {object} state - Object allowing you to keep state across function calls.
     */
    onLeave: function (log, retval, state) {
    }
}
